var lessons = [
  {
    id: 1,
    Subject: "Math",
    Location: "London",
    Price: 100,
    Space: 5,
    image: "images/math.jpg",
    icon: "fa-solid fa-calculator",
  },
  {
    id: 2,
    Subject: "English",
    Location: "Hendon",
    Price: 200,
    Space: 5,
    image: "images/english.jpg",
    icon: "fa-solid fa-spell-check",
  },
  {
    id: 3,
    Subject: "Science",
    Location: "London",
    Price: 100,
    Space: 5,
    image: "images/science.jpg",
    icon: "fa-solid fa-flask",
  },
  {
    id: 4,
    Subject: "Comp Sci",
    Location: "Birmingham",
    Price: 50,
    Space: 5,
    image: "images/computer.jpg",
    icon: "fa-solid fa-laptop",
  },
  {
    id: 5,
    Subject: "Science",
    Location: "Bristol",
    Price: 80,
    Space: 5,
    image: "images/science.jpg",
    icon: "fa-solid fa-flask",
  },
  {
    id: 6,
    Subject: "Music",
    Location: "Birmingham",
    Price: 90,
    Space: 5,
    image: "images/music.jpg",
    icon: "fa-solid fa-music",
  },
  {
    id: 7,
    Subject: "History",
    Location: "York",
    Price: 70,
    Space: 5,
    image: "images/history.jpg",
    icon: "fa-solid fa-hourglass-start",
  },
  {
    id: 8,
    Subject: "Math",
    Location: "Essex",
    Price: 120,
    Space: 5,
    image: "images/math.jpg",
    icon: "fa-solid fa-calculator",
  },
  {
    id: 9,
    Subject: "Geography",
    Location: "Oxford",
    Price: 75,
    Space: 5,
    image: "images/geography.jpg",
    icon: "fa-solid fa-globe",
  },
  {
    id: 10,
    Subject: "Music",
    Location: "London",
    Price: 145,
    Space: 5,
    image: "images/music.jpg",
    icon: "fa-solid fa-music",
  },
];
